# Generated by Django 6.0.5 on 2026-05-27 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='last_restocked',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='current_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=3, default=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('ltr', 'Liter (ltr)'), ('pcs', 'Pieces (pcs)'), ('gm', 'Gram (gm)'), ('ml', 'Milliliter (ml)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='quantity_required',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('purchase', 'Purchase/Restock'), ('usage', 'Consumption (Order)'), ('adjustment', 'Manual Adjustment'), ('waste', 'Wastage')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.ingredient')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
