# Generated by Django 6.0.5 on 2026-05-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ingredient_cost_per_unit_ingredient_last_restocked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='RestoManager', max_length=255)),
                ('tagline', models.CharField(blank=True, default='Authentic Cuisine', max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('currency_symbol', models.CharField(default='$', max_length=10)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('trn_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax Registration Number')),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Restaurant Setting',
                'verbose_name_plural': 'Restaurant Settings',
            },
        ),
    ]
