# Generated by Django 6.0.5 on 2026-06-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantsetting',
            name='currency_symbol',
            field=models.CharField(default='৳', max_length=10),
        ),
    ]
