# Generated by Django 6.0.5 on 2026-06-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_restaurantsetting_currency_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantsetting',
            name='currency_symbol',
            field=models.CharField(default='Tk ', max_length=10),
        ),
    ]
